#!/usr/bin/env python3
"""Soft Spaces Phase 2 v25.39 — Arb interval validation of v25.38.

Uses python-flint/Arb ball arithmetic with outward rounding to enclose the
eigenvalues, eigenvectors, spectral gaps, operator norms, base numerators,
base denominators, score-curvature constants, and positive prominence margins
for the frozen controlled-ancilla instances.

The validated object is the binary64 matrix instance generated by the frozen
v25.33 construction.  No score, coordinate, seed, family, coupling direction,
or interval radius is changed.
"""

from __future__ import annotations

import argparse
import math
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np

LOCAL_DEPS = Path(__file__).with_name("_interval_deps")
if LOCAL_DEPS.is_dir():
    sys.path.insert(0, str(LOCAL_DEPS))

try:
    from flint import acb, acb_mat, arb, ctx
except ImportError as exc:  # pragma: no cover - explicit dependency message
    raise SystemExit(
        "python-flint==0.9.0 is required; install requirements_v25_39.txt"
    ) from exc

import v25_33_exact_ancilla_lift_verification as base
import v25_34_controlled_coupling_stress_test as stress
import v25_38_continuum_score_curvature_bound as curvature


VERSION = "v25.39"
PRECISION_BITS = 256
VALIDATED_INTERVAL_RHO = {
    2533001: 1.0e-10,
    2533003: 3.0e-10,
    2533004: 1.0e-10,
}
REPORT_SAFETY_FACTOR = 0.89
RANK = 2


@dataclass(frozen=True)
class BallDecomposition:
    values: tuple[arb, ...]
    vectors: tuple[tuple[acb, ...], ...]  # normalized columns


@dataclass(frozen=True)
class BallParts:
    numerator: arb
    denominator: arb
    score: arb


@dataclass(frozen=True)
class BallScoreBound:
    curvature_upper: arb
    numerator_floor_lower: arb
    denominator_floor_lower: arb
    minimum_gap_lower: arb


@dataclass(frozen=True)
class ValidationResult:
    seed: int
    source_prominence_lower: arb | None
    source_prominence_upper: arb | None
    g_star_lower: arb | None
    interval_rho: float | None
    curvature_upper: arb | None
    numerator_floor_lower: arb | None
    denominator_floor_lower: arb | None
    minimum_gap_lower: arb | None
    certified_rho_lower: arb | None
    status: str


def lo(value: arb) -> arb:
    return value.lower()


def hi(value: arb) -> arb:
    return value.upper()


def positive(value: arb) -> bool:
    return float(lo(value)) > 0.0


def arb_min(values: list[arb]) -> arb:
    return min(values, key=lambda value: float(value))


def arb_max(values: list[arb]) -> arb:
    return max(values, key=lambda value: float(value))


def exact_acb_matrix(matrix: np.ndarray) -> acb_mat:
    return acb_mat([
        [acb(arb(float(value.real)), arb(float(value.imag))) for value in row]
        for row in matrix
    ])


def eigh_effective_hermitian(matrix: np.ndarray) -> np.ndarray:
    """Matrix actually represented by numpy.linalg.eigh(..., UPLO='L')."""
    lower = np.tril(matrix).copy()
    diagonal = np.diag_indices_from(lower)
    lower[diagonal] = lower[diagonal].real
    return lower + np.tril(lower, -1).conj().T


def decompose(matrix: np.ndarray) -> BallDecomposition:
    effective = eigh_effective_hermitian(matrix)
    eigenvalues, right = exact_acb_matrix(effective).eig(
        right=True, algorithm="rump"
    )
    order = sorted(
        range(len(eigenvalues)),
        key=lambda index: float(eigenvalues[index].real.mid()),
    )
    values: list[arb] = []
    vectors: list[tuple[acb, ...]] = []
    for index in order:
        value = eigenvalues[index]
        if not value.imag.contains(0):
            raise RuntimeError("Hermitian eigenvalue enclosure excludes the real axis")
        column = [right[row, index] for row in range(right.nrows())]
        norm2 = sum((entry.conjugate() * entry).real for entry in column)
        norm = norm2.sqrt()
        if not positive(norm):
            raise RuntimeError("Eigenvector norm enclosure contains zero")
        vectors.append(tuple(entry / norm for entry in column))
        values.append(value.real)
    return BallDecomposition(tuple(values), tuple(vectors))


def hermitian_norm_upper(matrix: np.ndarray) -> arb:
    effective = eigh_effective_hermitian(matrix)
    values = exact_acb_matrix(effective).eig(algorithm="rump")
    return arb_max([hi(abs(value)) for value in values])


def gap_between(values: tuple[arb, ...], lower_index: int, upper_index: int) -> arb:
    return lo(lo(values[upper_index]) - hi(values[lower_index]))


def individual_gap_lower(values: tuple[arb, ...], index: int) -> arb:
    gaps: list[arb] = []
    if index > 0:
        gaps.append(gap_between(values, index - 1, index))
    if index + 1 < len(values):
        gaps.append(gap_between(values, index, index + 1))
    return arb_min(gaps)


def cluster_gap_lower(values: tuple[arb, ...], left: int) -> arb:
    gaps: list[arb] = []
    if left > 0:
        gaps.append(gap_between(values, left - 1, left))
    if left + 2 < len(values):
        gaps.append(gap_between(values, left + 1, left + 2))
    return arb_min(gaps)


def cluster_gap_bounds(values: tuple[arb, ...], left: int) -> tuple[arb, arb]:
    gaps: list[arb] = []
    if left > 0:
        gaps.append(values[left] - values[left - 1])
    if left + 2 < len(values):
        gaps.append(values[left + 2] - values[left + 1])
    return (
        arb_min([lo(gap) for gap in gaps]),
        arb_min([hi(gap) for gap in gaps]),
    )


def matrix_vector(matrix: np.ndarray, vector: tuple[acb, ...]) -> list[acb]:
    result: list[acb] = []
    for row in range(matrix.shape[0]):
        total = acb(0)
        for column in range(matrix.shape[1]):
            value = matrix[row, column]
            total += acb(arb(float(value.real)), arb(float(value.imag))) * vector[column]
        result.append(total)
    return result


def inner(left: tuple[acb, ...], right: list[acb]) -> acb:
    return sum((a.conjugate() * b for a, b in zip(left, right)), acb(0))


def score_parts_ball(
    decomposition: BallDecomposition,
    perturbation: np.ndarray,
    left: int,
    eta: arb,
) -> BallParts:
    values = decomposition.values
    vectors = decomposition.vectors
    selected = (left, left + 1)
    transformed_selected = {
        selected_index: matrix_vector(perturbation, vectors[selected_index])
        for selected_index in selected
    }
    reference = (values[left] + values[left + 1]) / 2
    total = [[acb(0), acb(0)], [acb(0), acb(0)]]
    denominator = arb(0)
    for q_index in range(len(values)):
        if q_index in selected:
            continue
        couplings = [
            inner(vectors[q_index], transformed_selected[selected_index])
            for selected_index in selected
        ]
        delta = reference - values[q_index]
        weight = delta / (delta * delta + eta * eta)
        for row in range(2):
            for column in range(2):
                total[row][column] += (
                    weight * couplings[row].conjugate() * couplings[column]
                )
        denominator += abs(weight) * sum(
            (abs(coupling) ** 2 for coupling in couplings), arb(0)
        )
    numerator = sum(
        (abs(total[row][column]) ** 2 for row in range(2) for column in range(2)),
        arb(0),
    ).sqrt()
    if not positive(denominator):
        raise RuntimeError("Validated denominator enclosure contains zero")
    return BallParts(numerator, denominator, numerator / denominator)


def score_curvature_ball(
    decomposition: BallDecomposition,
    perturbation: np.ndarray,
    perturbation_norm_upper: arb,
    coupling_norm_upper: arb,
    left: int,
    interval_radius: arb,
    eta: arb,
) -> BallScoreBound:
    values = decomposition.values
    n = len(values)
    right = left + 1
    gap = cluster_gap_lower(values, left)
    width = hi(hi(values[right]) - lo(values[left]))
    rk = hi(interval_radius * coupling_norm_upper)
    contour_distance = lo(gap / 2 - rk)
    if not positive(contour_distance):
        raise RuntimeError("Rank-two contour distance is not positive")
    contour_length = hi(2 * width + arb.pi() * gap)
    p1 = hi(
        contour_length * coupling_norm_upper
        / (2 * arb.pi() * contour_distance**2)
    )
    p2 = hi(
        contour_length * coupling_norm_upper**2
        / (arb.pi() * contour_distance**3)
    )

    spectral_radius = hi((hi(values[-1]) - lo(values[0])) / 2 + rk)
    e1 = hi(coupling_norm_upper + 2 * spectral_radius * p1)
    e2 = hi(
        arb(n) / RANK
        * (spectral_radius * p2 + 2 * p1 * coupling_norm_upper)
    )
    bnorm = hi(2 * spectral_radius)
    a1 = hi(2 * p1 * bnorm + e1 + coupling_norm_upper)
    a2 = hi(
        2 * p2 * bnorm
        + 4 * p1 * (e1 + coupling_norm_upper)
        + 2 * p1**2 * bnorm
        + e2
    )

    m = perturbation_norm_upper
    t1 = hi(2 * m * p1)
    t2 = hi(2 * m * p2 + 2 * m * p1**2)
    g0 = hi(1 / (2 * eta))
    g1 = hi(a1 / eta**2)
    g2 = hi(2 * a1**2 / eta**3 + a2 / eta**2)
    effective1 = hi(2 * t1 * g0 * m + m**2 * g1)
    effective2 = hi(
        2 * t2 * g0 * m
        + m**2 * g2
        + 4 * t1 * g1 * m
        + 2 * t1**2 * g0
    )
    numerator1 = hi(arb(n).sqrt() * effective1)

    parts = score_parts_ball(decomposition, perturbation, left, eta)
    numerator_floor = lo(lo(parts.numerator) - interval_radius * numerator1)
    if not positive(numerator_floor):
        raise RuntimeError("Validated numerator floor is not positive")
    numerator2 = hi(
        arb(n).sqrt() * effective2
        + arb(n) * effective1**2 / numerator_floor
    )

    delta1 = hi(e1 + coupling_norm_upper)
    denominator1 = arb(0)
    denominator2 = arb(0)
    minimum_gap = gap
    reference_lower = lo((values[left] + values[right]) / 2)
    reference_upper = hi((values[left] + values[right]) / 2)
    for index in range(n):
        if index in (left, right):
            continue
        eigen_gap = individual_gap_lower(values, index)
        minimum_gap = arb_min([minimum_gap, eigen_gap])
        eig_contour_distance = lo(eigen_gap / 2 - rk)
        if not positive(eig_contour_distance):
            raise RuntimeError("Rank-one contour distance is not positive")
        q1 = hi(
            eigen_gap * coupling_norm_upper
            / (2 * eig_contour_distance**2)
        )
        q2 = hi(
            eigen_gap * coupling_norm_upper**2
            / eig_contour_distance**3
        )
        lambda2 = hi(
            2 * coupling_norm_upper**2 / (eigen_gap - 2 * rk)
        )
        delta2 = hi(e2 + lambda2)

        if index < left:
            abs_delta = lo(reference_lower - hi(values[index]))
        else:
            abs_delta = lo(lo(values[index]) - reference_upper)
        distance_from_zero = lo(abs_delta - 2 * rk)
        if not positive(distance_from_zero):
            raise RuntimeError("Weight argument may cross zero")
        scale2 = lo(distance_from_zero**2 + eta**2)
        h0 = hi(1 / scale2.sqrt())
        h1 = hi(1 / scale2)
        h2 = hi(6 / (scale2 * scale2.sqrt()))

        x1 = hi(m * (arb(2).sqrt() * q1 + 2 * p1))
        x2 = hi(
            m * (
                arb(n).sqrt() * q2
                + 2 * arb(2).sqrt() * q1 * p1
                + arb(n).sqrt() * p2
            )
        )
        coupling1 = hi(2 * m * x1)
        coupling2 = hi(2 * x1**2 + 2 * m * x2)
        denominator1 = hi(
            denominator1 + h1 * delta1 * m**2 + h0 * coupling1
        )
        denominator2 = hi(
            denominator2
            + h2 * delta1**2 * m**2
            + h1 * delta2 * m**2
            + 2 * h1 * delta1 * coupling1
            + h0 * coupling2
        )

    denominator_floor = lo(
        lo(parts.denominator) - interval_radius * denominator1
    )
    if not positive(denominator_floor):
        raise RuntimeError("Validated denominator floor is not positive")
    score_curvature = hi(
        (numerator2 + denominator2) / denominator_floor
        + 2 * (numerator1 * denominator1 + denominator1**2)
        / denominator_floor**2
    )
    return BallScoreBound(
        score_curvature,
        numerator_floor,
        denominator_floor,
        lo(minimum_gap),
    )


def median_upper(values: list[arb]) -> arb:
    ordered = sorted((hi(value) for value in values), key=float)
    return hi((ordered[2] + ordered[3]) / 2)


def median_lower(values: list[arb]) -> arb:
    ordered = sorted((lo(value) for value in values), key=float)
    return lo((ordered[2] + ordered[3]) / 2)


def validated_source_prominence_bounds(
    real_decomposition: BallDecomposition,
    null_decomposition: BallDecomposition,
    perturbations: dict[str, np.ndarray],
) -> tuple[arb, arb]:
    deltas: dict[tuple[str, int], arb] = {}
    for family, perturbation in perturbations.items():
        for index in (base.TARGET,) + base.CONTROLS:
            real_parts = score_parts_ball(
                real_decomposition, perturbation, index, arb(base.REGULARIZER)
            )
            null_parts = score_parts_ball(
                null_decomposition, perturbation, index, arb(base.REGULARIZER)
            )
            deltas[(family, index)] = real_parts.score - null_parts.score
    target_lower = arb_min([
        lo(deltas[(family, base.TARGET)]) for family in base.FAMILIES
    ])
    target_upper = arb_min([
        hi(deltas[(family, base.TARGET)]) for family in base.FAMILIES
    ])
    control_intervals: list[arb] = []
    for index in base.CONTROLS:
        lower = arb_min([lo(deltas[(family, index)]) for family in base.FAMILIES])
        upper = arb_min([hi(deltas[(family, index)]) for family in base.FAMILIES])
        control_intervals.append(arb((lower + upper) / 2, (upper - lower) / 2))
    return (
        lo(target_lower - median_upper(control_intervals)),
        hi(target_upper - median_lower(control_intervals)),
    )


def validate_seed(seed: int) -> ValidationResult:
    (
        _,
        _,
        h_real,
        h_null,
        perturbations,
        coupling,
    ) = curvature.build_instance(seed)
    real_dec = decompose(h_real)
    null_dec = decompose(h_null)
    # The lifted structures give exact norm reductions:
    # ||diag(V,V)||=||V|| and ||[[0,G],[G,0]]||=||G||.
    coupling_norm = hermitian_norm_upper(coupling[:base.DIM, base.DIM:])
    perturbation_norms = {
        family: hermitian_norm_upper(matrix[:base.DIM, :base.DIM])
        for family, matrix in perturbations.items()
    }

    indices = (base.TARGET,) + base.CONTROLS
    gap_bounds = [
        cluster_gap_bounds(real_dec.values, index + branch * base.DIM)
        for branch in (0, 1) for index in indices
    ]
    g_star = lo(arb_min([bounds[0] for bounds in gap_bounds]))
    g_star_upper = hi(arb_min([bounds[1] for bounds in gap_bounds]))

    # Source scores equal either exact lifted branch.  Compute them directly
    # on branch 0 using lifted matrices so the validated object is identical.
    lifted_source_perturbations = perturbations
    source_prominence, source_prominence_upper = validated_source_prominence_bounds(
        real_dec,
        null_dec,
        lifted_source_perturbations,
    )
    if seed not in VALIDATED_INTERVAL_RHO:
        if float(source_prominence_upper) >= 0.0:
            raise RuntimeError("Negative source prominence was not interval-validated")
        return ValidationResult(
            seed=seed,
            source_prominence_lower=source_prominence,
            source_prominence_upper=source_prominence_upper,
            g_star_lower=g_star,
            interval_rho=None,
            curvature_upper=None,
            numerator_floor_lower=None,
            denominator_floor_lower=None,
            minimum_gap_lower=None,
            certified_rho_lower=None,
            status="VALIDATED NEGATIVE — RETAINED, NOT ELIGIBLE",
        )

    interval_rho = VALIDATED_INTERVAL_RHO[seed]
    interval_radius = hi(arb(interval_rho) * g_star_upper)
    if not positive(source_prominence):
        raise RuntimeError("Validated source prominence is not positive")

    target_coefficients: list[arb] = []
    control_coefficients: list[arb] = []
    numerator_floors: list[arb] = []
    denominator_floors: list[arb] = []
    minimum_gaps: list[arb] = []
    eta = arb(base.REGULARIZER)
    for branch in (0, 1):
        offset = branch * base.DIM
        for family, perturbation in perturbations.items():
            for source_index in indices:
                left = source_index + offset
                real_bound = score_curvature_ball(
                    real_dec, perturbation, perturbation_norms[family],
                    coupling_norm, left, interval_radius, eta,
                )
                null_bound = score_curvature_ball(
                    null_dec, perturbation, perturbation_norms[family],
                    coupling_norm, left, interval_radius, eta,
                )
                coefficient = hi(
                    (real_bound.curvature_upper + null_bound.curvature_upper) / 2
                )
                if source_index == base.TARGET:
                    target_coefficients.append(coefficient)
                else:
                    control_coefficients.append(coefficient)
                for bound in (real_bound, null_bound):
                    numerator_floors.append(bound.numerator_floor_lower)
                    denominator_floors.append(bound.denominator_floor_lower)
                    minimum_gaps.append(bound.minimum_gap_lower)

    prominence_curvature = hi(
        arb_max(target_coefficients) + arb_max(control_coefficients)
    )
    margin_radius = lo((source_prominence / prominence_curvature).sqrt())
    safe_interval_radius = arb_min([interval_radius, margin_radius])
    certified_epsilon = lo(arb(REPORT_SAFETY_FACTOR) * safe_interval_radius)
    certified_rho = lo(certified_epsilon / g_star_upper)
    if not positive(certified_rho):
        raise RuntimeError("Certified rho enclosure is not positive")
    return ValidationResult(
        seed=seed,
        source_prominence_lower=source_prominence,
        source_prominence_upper=source_prominence_upper,
        g_star_lower=g_star,
        interval_rho=interval_rho,
        curvature_upper=prominence_curvature,
        numerator_floor_lower=arb_min(numerator_floors),
        denominator_floor_lower=arb_min(denominator_floors),
        minimum_gap_lower=arb_min(minimum_gaps),
        certified_rho_lower=certified_rho,
        status="VALIDATED",
    )


def sci(value: arb | None, digits: int = 8) -> str:
    if value is None:
        return "n/a"
    return f"{float(value):.{digits}e}"


def render(results: list[ValidationResult]) -> str:
    validated = [result for result in results if result.status == "VALIDATED"]
    lines = [
        "=== Soft Spaces Phase 2 v25.39 ARB INTERVAL VALIDATION ===",
        f"Arb precision: {PRECISION_BITS} bits; python-flint 0.9.0",
        f"Frozen target: {base.TARGET}; controls: {list(base.CONTROLS)}",
        f"Seeds: {list(base.BASE_SEEDS)}; families: {list(base.FAMILIES)}",
        "Validated object: exact binary64 matrices generated by the frozen v25.33 construction.",
        "All constants in VALIDATED rows use outward-rounded Arb/Acb balls.",
        "No fitting, coordinate relocation, re-ranking, seed removal, or interval enlargement.",
        "",
        "seed | status | prom lower/upper | g_star lower | interval rho | K upper | N floor lower | D floor lower | min gap lower | certified rho lower",
    ]
    for result in results:
        lines.append(
            f"{result.seed:7d} | {result.status:46s} | "
            f"{sci(result.source_prominence_lower):>12s}/{sci(result.source_prominence_upper):<12s} | "
            f"{sci(result.g_star_lower):>12s} | "
            f"{('n/a' if result.interval_rho is None else f'{result.interval_rho:.8e}'):>12s} | "
            f"{sci(result.curvature_upper):>12s} | "
            f"{sci(result.numerator_floor_lower):>13s} | "
            f"{sci(result.denominator_floor_lower):>13s} | "
            f"{sci(result.minimum_gap_lower):>13s} | "
            f"{sci(result.certified_rho_lower):>19s}"
        )
    common = arb_min([result.certified_rho_lower for result in validated]) if validated else None
    lines.extend([
        "",
        "DECISION",
        f"  Validated positive instances: {len(validated)}/3; validated negative instances retained: {len(results)-len(validated)}/2.",
        f"  Common outward-rounded certified rho lower bound: {sci(common)}.",
        "  Every reported lower floor is strictly positive and every spectral isolation inequality is evaluated with enclosed lower gaps.",
        "  The result upgrades the controlled-path numerical constant to a computer-assisted interval certificate for the frozen binary64 instances.",
        "  It does not prove a universal ensemble law and does not establish an intertwiner to the independent 8Q-12Q construction.",
    ])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("v25_39_arb_interval_validation_output.txt"),
    )
    args = parser.parse_args()
    ctx.prec = PRECISION_BITS
    results = [validate_seed(seed) for seed in base.BASE_SEEDS]
    report = render(results)
    print(report, end="")
    args.output.write_text(report, encoding="utf-8")


if __name__ == "__main__":
    main()
